version: '3'
services:
  app:
    image: websoftdevs/musicbot:prod
    command: ["python3", "app/app/main.py"]
    env_file:
      - .env
    ports:
      - "8001:8001"
    container_name: musicbot2
    network_mode: musicbot
