[tool.poetry]
name = "MusicBot2"
version = "0.0.1"
description = "Discord MusicBot2 - Poetry"
authors = ["Patryk Ladocha <patrykladocha76@gmail.com>"]

[tool.poetry.dependencies]
python = "3.11.2"
sqlalchemy = "1.4.44"
youtube_search = "2.1.2"
pydantic = "1.10.2"
yt-dlp = { git = "https://github.com/yt-dlp/yt-dlp", branch = "master" }
pynacl = "1.5.0"
'discord.py' = "2.2.2"

[tool.poetry.dev-dependencies]
pytest = "7.2.0"
pytest-cov = "4.0.0"
pre-commit = "2.20.0"
pylint = "2.15.5"
debugpy = "1.6.6"
ddiscord = "0.2.3"

[build-system]
requires = ["poetry>=1.3.2"]
build-backend = "poetry.masonry.api"
